version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - game-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - game-network

  skeeter:
    container_name: skeeter
    build:
      context: ./applications/skeeter
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
    networks:
      - game-network 
    env_file:
    - variables.env

  shooter1:
    container_name: shooter1
    build:
      context: ./applications/shooter
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - PYTHONUNBUFFERED=1
    ports:
      - 8001:8001
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
      - skeeter
    networks:
      - game-network 
    env_file:
    - variables.env

  shooter2:
    container_name: shooter2
    build:
      context: ./applications/shooter
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - PYTHONUNBUFFERED=1
    ports:
      - 8002:8002
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
      - skeeter
    networks:
      - game-network 
    env_file:
    - variables.env

  shooter3:
    container_name: shooter3
    build:
      context: ./applications/shooter
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - PYTHONUNBUFFERED=1
    ports:
      - 8003:8003
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
      - skeeter
    networks:
      - game-network 
    env_file:
    - variables.env

  shooter4:
    container_name: shooter4
    build:
      context: ./applications/shooter
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - PYTHONUNBUFFERED=1
    ports:
      - 8004:8004
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
      - skeeter
    networks:
      - game-network 
    env_file:
    - variables.env

  shooter5:
    container_name: shooter5
    build:
      context: ./applications/shooter
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - PYTHONUNBUFFERED=1
    ports:
      - 8005:8005
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
      - skeeter
    networks:
      - game-network 
    env_file:
    - variables.env     

  shooter6:
    container_name: shooter6
    build:
      context: ./applications/shooter
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - PYTHONUNBUFFERED=1
    ports:
      - 8006:8006
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
      - skeeter
    networks:
      - game-network 
    env_file:
    - variables.env 

  shooter7:
    container_name: shooter7
    build:
      context: ./applications/shooter
    environment:
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=9092
      - PYTHONUNBUFFERED=1
    ports:
      - 8007:8007
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
      - skeeter
    networks:
      - game-network 
    env_file:
    - variables.env 
    
networks:
  game-network:
    name: game-network
